# Generated by Django 4.2.5 on 2023-11-20 00:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_profile_income'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='balance',
        ),
    ]
